### ISSUE TITLE
Atualizar links da barra de navegação

### ISSUE THREAD

**Issue by DanielSalis** [UnifespCodeLab/emtu-web#22]
* Fazer com que os links redirecionem para as páginas certas

**Comment by IsadoraMuniz** [comment]
TODOs

- [ ] Fazer levantamento sobre quais serão de fato as opções que a sidenav mostrará (de acordo com as telas do figma)

- [ ] Confirmar se tem todas telas para redirecionar possuem esqueleto

- [ ] Estudar como realizar o método da chamada da rota
